[2025-09-15T10:12:18.360+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: spotify_saved_tracks_etl_pipeline.gold_saved_transform manual__2025-09-15T09:47:50.933492+00:00 [queued]>
[2025-09-15T10:12:18.374+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: spotify_saved_tracks_etl_pipeline.gold_saved_transform manual__2025-09-15T09:47:50.933492+00:00 [queued]>
[2025-09-15T10:12:18.376+0000] {taskinstance.py:1361} INFO - Starting attempt 5 of 6
[2025-09-15T10:12:18.526+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): gold_saved_transform> on 2025-09-15 09:47:50.933492+00:00
[2025-09-15T10:12:18.531+0000] {standard_task_runner.py:57} INFO - Started process 873 to run task
[2025-09-15T10:12:18.535+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'spotify_saved_tracks_etl_pipeline', 'gold_saved_transform', 'manual__2025-09-15T09:47:50.933492+00:00', '--job-id', '874', '--raw', '--subdir', 'DAGS_FOLDER/spotify_saved_dag.py', '--cfg-path', '/tmp/tmpatl3q_1q']
[2025-09-15T10:12:18.537+0000] {standard_task_runner.py:85} INFO - Job 874: Subtask gold_saved_transform
[2025-09-15T10:12:18.569+0000] {task_command.py:415} INFO - Running <TaskInstance: spotify_saved_tracks_etl_pipeline.gold_saved_transform manual__2025-09-15T09:47:50.933492+00:00 [running]> on host 537418afed42
[2025-09-15T10:12:18.629+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='spotify_saved_tracks_etl_pipeline' AIRFLOW_CTX_TASK_ID='gold_saved_transform' AIRFLOW_CTX_EXECUTION_DATE='2025-09-15T09:47:50.933492+00:00' AIRFLOW_CTX_TRY_NUMBER='5' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-09-15T09:47:50.933492+00:00'
[2025-09-15T10:12:18.642+0000] {logging_mixin.py:151} INFO - Executed sql/gold/saved_tracks/fact_saved_songs.sql
[2025-09-15T10:12:18.647+0000] {taskinstance.py:1943} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/etl/db_utils.py", line 11, in run_sql_scripts
    cur.execute(sql)
psycopg2.errors.DatatypeMismatch: column "song_duration_sec" is of type numeric but expression is of type text
LINE 9:     artist_id,
            ^
HINT:  You will need to rewrite or cast the expression.

[2025-09-15T10:12:18.654+0000] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=spotify_saved_tracks_etl_pipeline, task_id=gold_saved_transform, execution_date=20250915T094750, start_date=20250915T101218, end_date=20250915T101218
[2025-09-15T10:12:18.662+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 874 for task gold_saved_transform (column "song_duration_sec" is of type numeric but expression is of type text
LINE 9:     artist_id,
            ^
HINT:  You will need to rewrite or cast the expression.
; 873)
[2025-09-15T10:12:18.679+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2025-09-15T10:12:18.692+0000] {taskinstance.py:2784} INFO - 0 downstream tasks scheduled from follow-on schedule check
